### ISSUE TITLE
Jamoma won't be recognized by my win64 Pd

### ISSUE THREAD

**Issue by DanaGuen** [jamoma/JamomaPureData#46]
Hello,
I'm using a 64bit windows and running Pd-extended (0.43.4). I've been trying these days to install the Jamoma library (first 0.5.6 and then 1.0 beta 3)...unsuccessfully, every time I try to create a j. object I got an error message.  
I've tried:
- putting the Jamoma folder in the AppData\Roaming\Pd folder ((https://libraries.io/github/jamoma/JamomaPureData))
- putting it in C:\Program Files (x86)\Pd\extra
- putting it in C:\Program Files (x86)\Pd\lib
- putting it in C:\Program Files (x86)\Pd\startup
(and each time I precised those paths in Pd's preferences)
- restart the same with pd vanilla this time, by installing the library directly from the Find Menu 
I'm kind of desperate, knowing the fact I was able to run the library in 5 minutes on a osX...I like my pc and intend to keep it, but after searching I found that I should install Cmake (https://github.com/jamoma/Jamoma/wiki/Building-with-CMake#windows)...is that the only solution? 
Hope someone can help me!

**Comment by avilleret** [comment]
hi @DanaGuen 

JamomaPuredata is not maintained anymore and I strongly suggest to switch to [ossia](https://github.com/OSSIA/libossia) since it cover all JamomaPuredata feature with a very big jump in efficiency.
It's really easy to swap from Jamoma to Ossia since it uses the same model-view paradigm and all Jamoma object have their OSSIA counterpart (j.param -> ossia.param; j.remote -> ossia.remote and so on...).
The first release is planed for the end of the week, but if you can't wait, you can still try out the beta version from [github ](https://github.com/OSSIA/libossia/releases) or even more cutting edge, the [Appveyor build](https://ci.appveyor.com/project/JeanMichalCelerier/libossia/build/1.0.1224/job/ur5e75y1xug8l32y/artifacts) (which is busy at cooking right now, don't hesitate to checkout new build as they come).

Of course ossia comes with Max support but also SuperCollider, Python, Unity3d, openFrameworks, C and C++ API and is already included in awesome software like [Score](https://ossia.io/) (well, yes we are building it :-) )

Feel free to join us on https://gitter.im/OSSIA to chat or to report issue on [github](https://github.com/OSSIA/libossia/issues).

**Comment by DanaGuen** [comment]
Hi, thanks for answering so quickly!
Is there an equivalent in OSSIA for j.dbap? (I'm making a three dimensional dbap patch, hence the special need of the jamoma library). 
(I was at the presentation of Score in October, I'm from the ENSATT ^^)

**Comment by bltzr** [comment]
Hi @DanaGuen !
well, what's been ported to OSSIA is the so-called 'Modular' part of Jamoma.
So that doesn't include j.dbap
Anyhow, I guess that's probably just a matter of compiling it for your particular version, so, yep, installing Cmake might help, and it's not that bad actually
Hope this helped
